apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: felipemgilioli/hello-app:f63dc79e6330cd28db736fc90349141c25e053c5
        ports:
        - containerPort: 80
